### ISSUE TITLE
Plot TP properties by plane U, V, Z

### ISSUE THREAD

**Issue by adam-abed-abud** [DUNE-DAQ/tpgtools#16]
Currently the script [plot_tp_properties.py](https://github.com/DUNE-DAQ/tpgtools/blob/production/v4/scripts/plot_tp_properties.py) plots the distributions of all the TP properties (time-over-threshold, charge, ADC peak, etc.) together. It would be good to also have the plots separated by plane.

**Comment by virgolaema** [comment]
While doing it, I'm thinking I'd maybe be better to remove the `superimpose` option and default to what now is `superimpose==true`. One can always just analyse one run at the time and it's like not superimposing. What do you say?

**Comment by virgolaema** [comment]
PR #22 , but I just noticed that I called the planes U, V, X instead of Z. If Z is preferredm it's easy to change (just find and replace in plot_tp_properties.py), but let me know if you prefer me to do it.
