### ISSUE TITLE
Make automated pdf report of the TP properties

### ISSUE THREAD

**Issue by adam-abed-abud** [DUNE-DAQ/tpgtools#17]
Introduce in [plot_tp_properties.py](https://github.com/DUNE-DAQ/tpgtools/blob/production/v4/scripts/plot_tp_properties.py) a way to output all the results in a PDF document with the relevant information appended (file name, location, run number, etc.) 

Example for automated PDF reporting can be found for instance in the repository `performancetest`

**Comment by adam-abed-abud** [comment]
@aeoranday has implemented a simple script for the job. It should be worth merging the two scripts together.

**Comment by virgolaema** [comment]
I guess you are referring to the one in trgtools right? Or there is another one I didn't notice? 

about `performancetest`, you mean this notebook? https://github.com/DUNE-DAQ/performancetest/blob/5a09423e748c3cc23a992b7a3e2f64e6eea8b0d8/tools/Benchmark_report.ipynb#L93
