### ISSUE TITLE
Implement the functionality to output multiple frames of ADC data within the wibeth_tpg_algorithms_emulator app

### ISSUE THREAD

**Issue by kwawrows** [DUNE-DAQ/tpgtools#20]
Currently, wibeth_tpg_algorithms_emulator app can only output ADC data for a single frame.  Given the option to output TP data for a specified number of TRs it would be useful to have the corresponding ADC data for those TRs, for validation purposes.

**Comment by hristovaivana** [comment]
Thanks for the report and feature request. I take a look and will provide a proposed fix in a branch.

**Comment by hristovaivana** [comment]
The fix is in branch [hristova/tpg_pattgen_tools](https://github.com/DUNE-DAQ/tpgtools/tree/hristova/tpg_pattgen_tools). We close this.
